### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by SinaKhalili** [Haximilian/c_heap#1]
i thought you said you'd never make another side project in C??

**Comment by Haximilian** [comment]
Hey bro,

This was for a school project. An lru cache would use this heap. But now, I realize that an lru cache has better runtime if you use a linked list. So, this C project will be on the backburner for now.

I was adding a feature to my heap so you can update and delete values in the heap.

This project taught me about the double-free problem.

If you have two pointers to the same object, neither of the owners of the object can safely free the object. If both owners free the object, you get a double-free error. If the final owner of the resource frees it, you won't get any errors. But, the final owner can only be known at runtime. Hence, it cannot be known at compile time.

We can solve the problem with reference counts, smart pointers, and RAII.
